# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1URvNeptcXaajCFhguqbrKttrA6ZCxvHo
"""

pip install streamlit

import streamlit as st

import streamlit as st

st.title("Loan Sanction Prediction Application")
st.header("Machine Learning Model for Loan Approval")

st.write("This application predicts the likelihood of a loan being sanctioned.")
st.sidebar.header("User Input Features")